default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  user: hackathon
  password: password
  pool: 5

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
