default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 50

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
